---
- name: Update the package repository
  apt: update_cache=yes
  register: aptcache

- name: Install various useful tools everywhere
  apt: pkg={{ item }} state=installed
  when: aptcache|success
  with_items: "{{ pkg_to_install }}"

- name: Make sure conflicting packages are absent
  apt: pkg={{ item }} state=absent
  when: aptcache|success
  with_items: "{{ pkg_to_remove }}"

#- name: Disable the idiotic motd updating on every login
#  command: /bin/bash -c "cd /etc/pam.d && grep pam_motd * | grep -v # && perl -pi -e \'s/^/# / if /pam_motd/\' *"

- name: Copy the rc.local.sh script for sensors with Myricom
  when: cap_type == "myricom"
  copy: src=rc.local.myristart.sh dest=/usr/local/sbin/rc.local.sh owner=root group=root mode=0755 backup=yes
  register: rclocalscript

- name: Copy the rc.local.sh script for sensors with Intel
  when: cap_type == "pf_ring"
  copy: src=rc.local.offices.sh dest=/usr/local/sbin/rc.local.sh owner=root group=root mode=0755 backup=yes
  register: rclocalscript

- name: Copy the rc.local.sh script for full packet capture sensors
  when: nsm_role_pcap is defined
  copy: src=rc.local.pcap.sh dest=/usr/local/sbin/rc.local.sh owner=root group=root mode=0755 backup=yes
  register: rclocalscript

- name: Copy the rc.local.sh script for servers
  when: nsm_role_server is defined
  copy: src=rc.local.server.sh dest=/usr/local/sbin/rc.local.sh owner=root group=root mode=0755 backup=yes
  register: rclocalscript

- name: Start the rc.local script at boot while preserving the original
  when: rclocalscript|success
  lineinfile: dest=/etc/rc.local regexp="^\/usr\/local\/sbin\/rc\.local\.sh" insertbefore=BOF line='/usr/local/sbin/rc.local.sh' backup=yes mode=0755 state=present owner=root group=root

