---
- name: Create necessary server directories
  when: nsm_role_server is defined
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    "{{ nsm_server_dirs }}"
  register: nsmserverdirs

- name: Copy intelzilla fetch and deploy files
  when: (nsm_role_server is defined and nsmserverdirs|success)
  copy: src={{ item }} dest=/usr/local/sbin/{{ item }} owner=root group=root mode=0755
  with_items:
    - criticalstackupdate.sh
    - idsrulesupdate.sh
    - iqriskupdate.py
  register: nsmserverscripts

- name: Create idsrulesupdate cron job
  when: nsmserverscripts|success
  cron: name="idsrulesupdate" hour="4" minute="10" job={{ nsm_scripts_path }}/idsrulesupdate.sh cron_file="idsrulesupdate" user="root"

- name: Create criticalstackpull cron job
  when: nsmserverscripts|success
  cron: name="criticalstackpull" hour="4" minute="11" job={{ nsm_scripts_path }}"/critical-stack-intel pull" cron_file="criticalstackpull" user="root"

- name: Create criticalstackupdate cron job
  when: nsmserverscripts|success
  cron: name="criticalstackupdate" hour="4" minute="14" job={{ nsm_scripts_path }}/criticalstackupdate.sh cron_file="criticalstackupdate" user="root"

- name: Create iqriskupdate cron job
  when: nsmserverscripts|success
  cron: name="iqriskupdate" hour="4" minute="17" job={{ nsm_scripts_path }}/iqriskupdate.py cron_file="iqriskupdate" user="root"

